### PR TITLE
Fix Electrum RPC Hang

### PR DESCRIPTION
**Pull request by junderw**
Edit: This PR by itself has a bug that was fixed in #49 

---

This works now.

SIGINT shuts everything down within a few milliseconds. (I only had one active connection from my local Sparrow wallet though)

You can test it by:

1. Build and run it, be sure to pass in --electrum-rpc-addr "0.0.0.0:50001" etc to allow your electrs to listen outside the container if using docker etc. (also expose the ports)
2. Wait until it says Electrum RPC started.
3. Run commands below to pummel the server with electrum requests. Wait for maybe 10 seconds or so before sending SIGINT.
4. Send a SIGINT. Pre-merge, it would freeze and not shutdown. Post-merge, the process will shut down in a few milliseconds.

## Commands

```
# Make a temp folder and cd to it
cd $(mktemp -d)

# create a new rust project
cargo new electrs-pummeler

cd electrs-pummeler

cargo add electrum-client@0.18

##### Enter the Rust code below into main.rs

# Only run the code after the Electrum RPC is listening on 50001 localhost
cargo run --release
```

```rust
use electrum_client::{bitcoin::Script, Client, ElectrumApi};
use std::thread::{sleep, spawn};
use std::time::Duration;

const LONG_WAIT_MS: u64 = 600_000;
const TINY_WAIT_MS: u64 = 10;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    for _ in 0..5000 {
        spawn(move || {
            let _client = run_new_client_in_loop("tcp://127.0.0.1:50001").unwrap();

            sleep(Duration::from_millis(LONG_WAIT_MS));
        });
        sleep(Duration::from_millis(TINY_WAIT_MS));
    }
    sleep(Duration::from_millis(LONG_WAIT_MS));
    Ok(())
}

fn run_new_client_in_loop(url: &str) -> Result<Client, Box<dyn std::error::Error>> {
    let client = Client::new(url)?;

    let _ = client.block_headers_subscribe()?;
    let mut script_bytes = [0x04, 0, 0, 0, 0];
    let mut subs = Vec::with_capacity(256);
    for i in 0..=255u8 {
        script_bytes[4] = i;
        subs.push(client.script_subscribe(Script::from_bytes(&script_bytes))?);
    }
    Ok(client)
}
```

### CODE REVIEW

**Comment by junderw** [comment]
After some testing, it seems to be dropping Electrum connections every time it times out to check the shutdown channel...

Causing the clients to reconnect frequently.

I'm going to keep hacking at it over the weekend.

**Comment by junderw** [comment]
This works now.

SIGINT shuts everything down within a few milliseconds. (I only had one active connection from my local Sparrow wallet though)

You can test it by:

1. Build and run it, be sure to pass in `--electrum-rpc-addr "0.0.0.0:50001"` etc to allow your electrs to listen outside the container if using docker etc. (also expose the ports)
2. Wait until it says Electrum RPC started.
3. Open Sparrow Wallet and set connection to 127.0.0.1:50001 with TLS disabled. You should see logs periodically if you use TRACE logging.
4. Send a SIGINT. Pre-merge, it would freeze and not shutdown. Post-merge, the process will shut down in a few milliseconds.

**Comment by junderw** [comment]
Oops I think I accidentally reverted a commit on mempool branch. Ill fix it later

**Review by mononaut — APPROVED** [review]
Tested ACK @ 0af9038a

I was able to reproduce the hang ~50% of the time on master using the pummeler, but not at all running this PR.

I don't fully understand all of the code changes, but it seems to run fine and doesn't break the RPC API as far as I can tell (if anything, RPC commands/subscriptions feel faster).

**Review by softsimon — APPROVED** [review]
tested ACK @ [0af9038a5]

**Pull request merged**
