### PR TITLE
Fix: Parse the inner witness_script properly for p2tr

### PR DESCRIPTION
**Pull request by junderw**
Fixes:
https://github.com/mempool/mempool/issues/2641
https://github.com/mempool/mempool/issues/2380
https://github.com/mempool/mempool/issues/1748

---

### Affects API interface AND/OR response data format? == **No**

---

@softsimon @wiz 

TODO:

- [x] account for annex and key spend.

### CODE REVIEW

**Comment by junderw** [comment]
Note: this code is only used in `rest.rs` despite being defined outside of it.

**Comment by junderw** [comment]
Done. Ready for merge... who should/can review?

**Comment by junderw** [comment]
Seems like @shesek is inactive.

Maybe @Kixunil or @tcharding would be willing to review?

**Comment by Kixunil** [comment]
Sorry, I have no affiliation with Mempool's fork of `electrs`. I took a **very light** look at the code and I see no obvious issues like non-idiomatic Rust or bad perf but I didn't check the logic at all.

**Comment by junderw** [comment]
> Sorry, I have no affiliation with Mempool's fork of `electrs`. I took a **very light** look at the code and I see no obvious issues like non-idiomatic Rust or bad perf but I didn't check the logic at all.

Even a very light once over is better than nothing.

Thanks a ton!

**Comment by tcharding** [comment]
I don't even have an affiliation with the original `electrs` :) I did a super light review also.

**Comment by junderw** [comment]
Now that the "none" backend (bitcoind) shows p2tr scripts properly, we should merge this so production does as well.

@softsimon @wiz (See: https://github.com/mempool/mempool/pull/3830)

**Review by softsimon — APPROVED** [review]
tested ACK @ [c876aca3]

Screenshot 2023-06-06 at 19 16 15

**Pull request merged**
