### PR TITLE
Fix thread leaks: Close channel without taking ownership of self.

### PR DESCRIPTION
**Pull request by junderw**
Another fix for #48 and #49 

This should fix all other cases.

### CODE REVIEW

**Comment by junderw** [comment]
Self tested ACK 2868de0

SIGINT will clear out all the threads when using the pummeler.

**Comment by junderw** [comment]
Self tested ACK da1c9b7182c07a9744944ed60ffd5a39e071d922

**Comment by junderw** [comment]
Self tested ACK 32f7830

**Comment by wiz** [comment]
Merged in #50

**Pull request closed without merging**
